# c.f. https://openapi-generator.tech/docs/generators/typescript-fetch
modelPropertyNaming: 'camelCase'
paramNaming: 'camelCase'
enumPropertyNaming: 'camelCase'
snapshot: true
supportsES6: true
useSingleRequestParameter: true
withInterfaces: true
