import { marker } from './types';

export const markers: marker[] = [
  {
    color: '#6ab840',
    description: '道路が崩れています。',
    imgUrl: '/image_cracked-road.webp',
    latitude: 33.591,
    longitude: 130.419,
    postedAt: new Date(),
    postedBy: 'サンプルユーザ1',
    problemName: '道路',
  },
  {
    color: '#3182CE',
    description: '犬が迷子になっています。',
    latitude: 33.591,
    longitude: 130.421,
    postedAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 1),
    postedBy: 'サンプルユーザ2',
    problemName: '動物',
  },
  {
    color: 'orange',
    description: 'ゴミが捨てられています。',
    latitude: 33.592,
    longitude: 130.422,
    postedAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 2),
    postedBy: 'サンプルユーザ3',
    problemName: 'ごみ',
  },
  {
    color: '#6ab840',
    description: '道路が崩れています。',
    imgUrl: '/image_cracked-road.webp',
    latitude: 33.589,
    longitude: 130.412,
    postedAt: new Date(),
    postedBy: 'サンプルユーザ1',
    problemName: '道路',
  },
  {
    color: '#3182CE',
    description: '犬が迷子になっています。',
    latitude: 33.588,
    longitude: 130.42,
    postedAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 1),
    postedBy: 'サンプルユーザ2',
    problemName: '動物',
  },
  {
    color: 'orange',
    description: 'ゴミが捨てられています。',
    latitude: 33.595,
    longitude: 130.414,
    postedAt: new Date(new Date().getTime() + 1000 * 60 * 60 * 24 * 2),
    postedBy: 'サンプルユーザ3',
    problemName: 'ごみ',
  },
];
