import { admin } from './type';

export const admins: admin[] = [
  {
    department: '総務課',
    email: 'admin@prefecture.jp',
    fullName: '総務部長 太郎',
    id: 1,
    isActive: true,
    isSuperuser: true,
  },
  {
    department: '市民課',
    email: 'citizen@prefecture.jp',
    fullName: '市民課担当者 花子',
    id: 2,
    isActive: true,
    isSuperuser: false,
  },
  {
    department: '福祉課',
    email: 'welfare@prefecture.jp',
    fullName: '福祉課長 次郎',
    id: 3,
    isActive: true,
    isSuperuser: false,
  },
  {
    department: '教育課',
    email: 'education@prefecture.jp',
    fullName: '教育課リーダー 三郎',
    id: 4,
    isActive: true,
    isSuperuser: false,
  },
  {
    department: '防災課',
    email: 'disaster@prefecture.jp',
    fullName: '防災課チーフ 四郎',
    id: 5,
    isActive: true,
    isSuperuser: false,
  },
  {
    department: '観光課',
    email: 'tourism@prefecture.jp',
    fullName: '観光課長 五郎',
    id: 6,
    isActive: true,
    isSuperuser: false,
  },
  {
    department: '産業振興課',
    email: 'industry@prefecture.jp',
    fullName: '産業振興課マネージャー 六郎',
    id: 7,
    isActive: true,
    isSuperuser: false,
  },
  {
    department: '環境課',
    email: 'environment@prefecture.jp',
    fullName: '環境課リーダー 七郎',
    id: 8,
    isActive: true,
    isSuperuser: false,
  },
  {
    department: '農林水産課',
    email: 'agriculture@prefecture.jp',
    fullName: '農林水産課職員 八郎',
    id: 9,
    isActive: false,
    isSuperuser: false,
  },
  {
    department: '健康課',
    email: 'health@prefecture.jp',
    fullName: '健康課管理者 九郎',
    id: 10,
    isActive: true,
    isSuperuser: false,
  },
];
