name: Backend CI

defaults:
  run:
    working-directory: backend

on:
  pull_request:
    paths:
      - "backend/**"
  push:
    paths:
      - "backend/**"
    branches-ignore:
      - main

jobs:
  # test, docker buildなどは実施しない
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort
      
      - name: Run isort
        run: isort ./ --profile black --skip ./app/tests
      
      - name: Run black
        run: black ./ --line-length 88 --exclude ./app/tests

      - name: Run flake8
        run: flake8 ./ --exclude ./app/tests --max-line-length=88 --ignore=E203,W503,W504

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy

      - name: Run mypy
        run: mypy ./
        