name: Frontend CI

defaults:
  run:
    working-directory: frontend

on:
  pull_request:
    paths:
      - "frontend/**"
  push:
    paths:
      - "frontend/**"
    branches-ignore:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - lint
          - build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Install dependencies
        run: yarn install

      # NOTE: src/gen/$path.tsを生成
      - name: Generate files
        if: ${{ matrix.command != 'build' }}
        run: yarn build:common:gen

      - name: Run ${{ matrix.command }}
        run: yarn ${{ matrix.command }}
